# Generated by Django 4.2.4 on 2023-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_alter_characterdetails_char_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_img',
            field=models.CharField(max_length=1000),
        ),
    ]
