# Generated by Django 4.2.4 on 2023-09-19 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0009_alter_characterdetails_char_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='char_poster',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
