# Generated by Django 4.2.4 on 2023-09-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
