# Generated by Django 4.2.4 on 2023-09-09 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_character_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.IntegerField()),
                ('char_name', models.CharField(max_length=50)),
                ('char_bounty', models.CharField(max_length=18)),
                ('char_img', models.CharField(max_length=100)),
                ('char_fruitname', models.CharField(max_length=50)),
                ('char_desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='char_img',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
