# Generated by Django 4.2.4 on 2023-09-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_characterdetails_character_char_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdetails',
            name='char_desc',
            field=models.CharField(max_length=10000),
        ),
    ]
